name: Deploy VitePress Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'  # Or the Node.js version you prefer

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run docs:build
